site_name: 咸鱼云网盘
theme:
  name: material
  features:
#    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.expand
#    - navigation.sections
#    - navigation.indexes

nav:
  - 简介: index.md
  - 快速开始:
    - quick-start/index.md
    - 配置参数: quick-start/config.md
    - 关于前端: quick-start/front-end.md
    - 衍生项目: quick-start/other.md
  - 插件:
      - extension/index.md
      - 插件：mp3-thumbnail: extension/mp3-thumbnail.md
      - 插件：hadoop-store: extension/hadoop-store.md
      - 插件：minio-store: extension/minio-store.md
      - 插件：samba-store: extension/samba-store.md
  - 开发手册:
      - develop/index.md
      - 项目构建: develop/build.md