server:
  port: 8087
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/disk?useSSL=false&serverTimezone=UTC
      username: user
      password: password
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
  servlet:
    multipart:
      max-file-size: 8192MB
      max-request-size: 8192MB
logging:
  level:
    org: warn
    com: warn
    com.xiaotao: info
    com.xiaotao.saltedfishcloud.SaltedfishcloudApplication: warn
app:
  version: ^project.version^
