server:
  port: 8087
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  tomcat:
    remoteip:
      remote-ip-header: X-Real-IP
spring:
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/t_xyy?useSSL=false&serverTimezone=UTC
      username: root
      password:
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
  servlet:
    multipart:
      max-file-size: 8192MB
      max-request-size: 8192MB
logging:
  level:
    org: warn
    com: warn
    com.xiaotao: info
#    com.xiaotao.saltedfishcloud.dao.mybatis: warn
    com.xiaotao.saltedfishcloud.SaltedfishcloudApplication: warn
app:
  version: ^project.version^


sys:
  common:
    # 注册邀请码
    reg-code: 114514
  sync:
    # 自动同步间隔，单位分钟，-1表示关闭自动同步
    interval: -1

    # 咸鱼云启动时立即同步，默认关闭
    sync-on-launch: false
  store:
    # 压缩文件操作使用的文件编码格式，默认使用系统默认编码，Linux: UTF-8，Windows: GBK
    archive-encoding: utf-8

    # 存储服务类型，可选hdfs（需要hdfs拓展）或local
    type: local

    # 各类资源根目录存储路径
    root: store

    # 公共网盘根目录路径
    public-root: public

    # 存储模式，可选 raw - 原始存储 或 unique - 唯一存储
    mode: unique
  ftp:
    # FTP控制端口
    control-port: 21

    # FTP监听地址
    listen-addr: 0.0.0.0

    # 是否开启FTP
    ftp-enable: true

    # FTP被动模式传输重定向地址
    passive-addr: localhost

    # FTP被动模式传输端口范围
    passive-port: 20000-30000
